# Reconstructs time from an event log. Reads timestamp-sorted TSVs on stdin.
#   -v since=EPOCH  -v upto=EPOCH  -v gap=SECONDS
#   -v reading_wpm=NUMBER  -v max_reading=SECONDS  -v max_active=SECONDS
#   -v byday=0|1  -v detail=0|1
BEGIN { FS = "\t" }

# Intervals are queued until END because report-only day-boundary rows are mixed
# into the timestamp-sorted stream and may arrive after an earlier interval.
function queue_interval(project, subpath, mode, first, last, estimated) {
  if (last <= first) return
  ni++
  iproject[ni] = project; isubpath[ni] = subpath; imode[ni] = mode
  ifirst[ni] = first; ilast[ni] = last; iestimated[ni] = estimated
}

function queue_touch(project, subpath, at) {
  nt++
  tproject[nt] = project; tsubpath[nt] = subpath; tat[nt] = at
}

function project_key(project, subpath,   key) {
  key = project
  if (detail && subpath != ".") key = project "/" subpath
  return key
}

function day_at(epoch,   i, day) {
  day = ""
  for (i = 1; i <= nbound; i++) {
    if (bound[i] > epoch) break
    day = boundday[i]
  }
  return day
}

function touch(bucket) {
  if (bucket == "") return
  if (!(bucket in seen)) { seen[bucket] = 1; keys[++nkeys] = bucket }
}

function add_raw(bucket, mode, secs, estimated) {
  if (secs <= 0) return
  touch(bucket)
  total[bucket, mode] += secs
  if (estimated) estimate[bucket] += secs
}

# Clip first, then divide at every real local-day boundary. Estimated reading
# is a paired subset, so it contributes once to paired/total and once to the
# non-additive estimate disclosure column.
function add_interval(project, subpath, mode, first, last, estimated,
                      cursor, finish, i, bucket) {
  if (first < since) first = since
  if (last > upto) last = upto
  if (last <= first) return

  if (!byday) {
    add_raw(project_key(project, subpath), mode, last - first, estimated)
    return
  }

  cursor = first
  while (cursor < last) {
    finish = last
    for (i = 1; i <= nbound; i++) {
      if (bound[i] > cursor) {
        if (bound[i] < finish) finish = bound[i]
        break
      }
    }
    bucket = day_at(cursor)
    add_raw(bucket, mode, finish - cursor, estimated)
    cursor = finish
  }
}

function id_value(value) { return (value == "" || value == "-") ? "*" : value }
function ids_match(active, terminal) {
  return active == "*" || terminal == "*" || active == terminal
}

# Synthetic rows are generated by bin/tt only for --by day. Their epoch is the
# actual first instant of a local day, including DST days without 00:00.
$2 == "boundary" {
  bound[++nbound] = $3 + 0
  boundday[nbound] = $1
  next
}

NF < 11 { next }

$2 == "span" {
  queue_interval($8, $9, "manual", $3 + 0, $4 + 0, 0)
  next
}

$2 != "beat" { next }

{
  at = $3 + 0
  machine = $5; harness = $6; mode = $7; project = $8; subpath = $9
  session = $10; event = $11
  turn = (NF >= 12 ? id_value($12) : "*")
  tool = (NF >= 13 ? id_value($13) : "*")
  agent = (NF >= 14 ? id_value($14) : "*")
  words = (NF >= 16 ? $16 : "-")
  session_source = (NF >= 17 ? $17 : "-")
  stream = machine SUBSEP harness SUBSEP session SUBSEP project SUBSEP subpath

  queue_touch(project, subpath, at)

  # A resumed session keeps its id, and the id is part of the stream key, so a
  # SessionStart can arrive after a turn that no terminal event ever closed.
  # Codex also emits SessionStart with source=compact while the same turn is
  # still running; that continuation must preserve the active lifecycle state.
  if (event == "SessionStart" &&
      !(harness == "codex" && session_source == "compact")) {
    active_turn[stream] = ""
    lifecycle_epoch[stream]++
    active_tools[stream] = 0
    active_agents[stream] = 0
  }

  if (stream in previous_at) {
    elapsed = at - previous_at[stream]
    proven = (active_turn[stream] != "" || active_tools[stream] > 0 || active_agents[stream] > 0)

    # A prompt arriving while a different turn is still open proves that the
    # earlier turn ended without recording a terminal event -- an interrupt, or
    # a harness that has no hook for one. Its end is unknown, so the gap falls
    # back to the idle rule instead of counting as the agent working. Wildcard
    # ids, which is what a legacy row carries, never trigger this.
    if (event == "UserPromptSubmit" && active_turn[stream] != "" &&
        !ids_match(active_turn[stream], turn))
      proven = 0

    # Stop ends known activity. Only a timely paired Stop-to-prompt gap is
    # inferred as review/composition; a solo return is handled by its bounded
    # estimate below, and other post-Stop gaps remain idle.
    if (previous_event[stream] == "Stop") {
      inferred = (event == "UserPromptSubmit" && previous_mode[stream] == "paired" && elapsed <= gap)
      proven = 0
    } else {
      inferred = (elapsed <= gap)
    }

    # Activity proven by an open turn, tool or subagent counts regardless of
    # TT_IDLE_GAP, so the ceiling is what stops an event that never arrived from
    # counting unbounded time. Counting runs forward from the beat that proved
    # the activity, so a genuinely long tool call keeps the ceiling's worth of
    # it rather than being discarded whole.
    count_to = at
    if (proven && max_active > 0 && elapsed > max_active)
      count_to = previous_at[stream] + max_active

    if (elapsed > 0 && (proven || inferred))
      queue_interval(previous_project[stream], previous_subpath[stream],
                     previous_mode[stream], previous_at[stream], count_to, 0)
  }

  # A reading estimate is created only when the very next event on this stream
  # is the user's return. This prevents overlap with later observed activity.
  if (event == "UserPromptSubmit" && stream in pending_stop) {
    elapsed = at - pending_stop[stream]
    if (elapsed > 0 && reading_wpm > 0 &&
        pending_words[stream] ~ /^[0-9]+$/ && pending_words[stream] > 0) {
      seconds = int(pending_words[stream] * 60 / reading_wpm + 0.5)
      if (seconds > elapsed) seconds = elapsed
      if (seconds > max_reading) seconds = max_reading
      queue_interval(pending_project[stream], pending_subpath[stream], "paired",
                     at - seconds, at, 1)
    }
    delete pending_stop[stream]
    delete pending_words[stream]
    delete pending_project[stream]
    delete pending_subpath[stream]
  } else if (event != "Stop" && stream in pending_stop && at > pending_stop[stream]) {
    delete pending_stop[stream]
    delete pending_words[stream]
    delete pending_project[stream]
    delete pending_subpath[stream]
  }

  # Update lifecycle state after measuring the interval ending at this
  # event. Starts prove activity forward; matching terminal events close it at
  # their own timestamp.
  if (event == "UserPromptSubmit") {
    active_turn[stream] = turn
  } else if (event == "Stop" || event == "Interrupt" || event == "StopFailure") {
    if (active_turn[stream] == "" || ids_match(active_turn[stream], turn)) {
      active_turn[stream] = ""
      lifecycle_epoch[stream]++
      active_tools[stream] = 0
      active_agents[stream] = 0
    }
  } else if (event == "SessionEnd") {
    active_turn[stream] = ""
    lifecycle_epoch[stream]++
    active_tools[stream] = 0
    active_agents[stream] = 0
  }

  if (event == "PreToolUse") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP tool
    if (!tool_open[lifecycle_key]) {
      tool_open[lifecycle_key] = 1
      active_tools[stream]++
    }
  } else if (event == "PostToolUse" || event == "PostToolUseFailure" ||
             event == "PermissionDenied") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP tool
    if (tool_open[lifecycle_key]) {
      delete tool_open[lifecycle_key]
      if (active_tools[stream] > 0) active_tools[stream]--
    } else if (tool == "*" && active_tools[stream] > 0) {
      # A terminal event carrying no tool id names no single open call, so it
      # closes them all. Leaving them open would prove activity indefinitely.
      active_tools[stream] = 0
    }
  }

  if (event == "SubagentStart") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP agent
    if (!agent_open[lifecycle_key]) {
      agent_open[lifecycle_key] = 1
      active_agents[stream]++
    }
  } else if (event == "SubagentStop") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP agent
    if (agent_open[lifecycle_key]) {
      delete agent_open[lifecycle_key]
      if (active_agents[stream] > 0) active_agents[stream]--
    }
  }

  if (event == "Stop") {
    if (mode == "solo" && words ~ /^[0-9]+$/ && words > 0) {
      pending_stop[stream] = at
      pending_words[stream] = words
      pending_project[stream] = project
      pending_subpath[stream] = subpath
    } else {
      delete pending_stop[stream]
      delete pending_words[stream]
      delete pending_project[stream]
      delete pending_subpath[stream]
    }
  }

  previous_at[stream] = at
  previous_mode[stream] = mode
  previous_event[stream] = event
  previous_project[stream] = project
  previous_subpath[stream] = subpath
}

function hm(seconds,   hours, minutes) {
  hours = int(seconds / 3600)
  minutes = int((seconds % 3600) / 60)
  return sprintf("%dh %02dm", hours, minutes)
}

END {
  for (i = 1; i <= nt; i++) {
    if (tat[i] < since || tat[i] >= upto) continue
    if (byday) touch(day_at(tat[i]))
    else touch(project_key(tproject[i], tsubpath[i]))
  }

  for (i = 1; i <= ni; i++)
    add_interval(iproject[i], isubpath[i], imode[i], ifirst[i], ilast[i], iestimated[i])

  # Insertion sort avoids depending on gawk's asorti().
  for (i = 2; i <= nkeys; i++) {
    value = keys[i]; j = i - 1
    while (j >= 1 && keys[j] > value) { keys[j + 1] = keys[j]; j-- }
    keys[j + 1] = value
  }

  width = 7
  for (i = 1; i <= nkeys; i++) if (length(keys[i]) > width) width = length(keys[i])
  format = "%-" width "s  %9s %9s %9s %9s %9s\n"

  if (nkeys > 0)
    printf format, (byday ? "DAY" : "PROJECT"), "PAIRED", "SOLO", "MANUAL", "ESTIMATED", "TOTAL"

  grand_paired = 0; grand_solo = 0; grand_manual = 0; grand_estimate = 0
  for (i = 1; i <= nkeys; i++) {
    key = keys[i]
    paired = total[key, "paired"] + 0
    solo = total[key, "solo"] + 0
    manual = total[key, "manual"] + 0
    estimated = estimate[key] + 0
    grand_paired += paired; grand_solo += solo; grand_manual += manual
    grand_estimate += estimated
    printf format, key, hm(paired), hm(solo), hm(manual), hm(estimated), hm(paired + solo + manual)
  }

  if (nkeys > 0)
    printf format, "TOTAL", hm(grand_paired), hm(grand_solo), hm(grand_manual),
           hm(grand_estimate), hm(grand_paired + grand_solo + grand_manual)
  else print "no events in range"
}
