# Reconstructs time from timestamp-sorted detail, totals, and carry state.
#   -v since=EPOCH  -v upto=EPOCH  -v gap=SECONDS
#   -v reading_wpm=NUMBER  -v max_reading=SECONDS  -v max_active=SECONDS
#   -v byday=0|1  -v detail=0|1
#   -v output_mode=report|compact|state
BEGIN {
  FS = "\t"
  if (output_mode == "") output_mode = "report"
}

# Intervals are queued until END because report-only day-boundary rows are mixed
# into the timestamp-sorted stream and may arrive after an earlier interval.
function queue_interval(project, subpath, mode, first, last, estimated) {
  if (last <= first) return
  ni++
  iproject[ni] = project; isubpath[ni] = subpath; imode[ni] = mode
  ifirst[ni] = first; ilast[ni] = last; iestimated[ni] = estimated
}

function queue_total(project, subpath, mode, first, last, seconds, estimated) {
  if (seconds <= 0) return
  nsummary++
  sproject[nsummary] = project; ssubpath[nsummary] = subpath
  smode[nsummary] = mode; sfirst[nsummary] = first; slast[nsummary] = last
  sseconds[nsummary] = seconds; sestimated[nsummary] = estimated
}

function project_key(project, subpath,   key) {
  key = project
  if (detail && subpath != ".") key = project "/" subpath
  return key
}

function day_at(epoch,   i, day) {
  day = ""
  for (i = 1; i <= nbound; i++) {
    if (bound[i] > epoch) break
    day = boundday[i]
  }
  return day
}

function touch(bucket) {
  if (bucket == "") return
  if (!(bucket in seen)) { seen[bucket] = 1; keys[++nkeys] = bucket }
}

function add_raw(bucket, mode, secs, estimated) {
  if (secs <= 0) return
  touch(bucket)
  total[bucket, mode] += secs
  if (estimated) estimate[bucket] += secs
}

function compact_key(day, project, subpath,   key) {
  key = day SUBSEP project SUBSEP subpath
  cday[key] = day; cproject[key] = project; csubpath[key] = subpath
  return key
}

function add_compact(day, project, subpath, mode, secs, estimated_secs,
                     key) {
  if (day == "" || secs <= 0) return
  key = compact_key(day, project, subpath)
  touch(key)
  total[key, mode] += secs
  if (estimated_secs > 0) estimate[key] += estimated_secs
}

# Clip first, then divide at every real local-day boundary. Estimated reading
# is a paired subset, so it contributes once to paired/total and once to the
# non-additive estimate disclosure column.
function add_interval(project, subpath, mode, first, last, estimated,
                      cursor, finish, i, bucket, day) {
  if (first < since) first = since
  if (last > upto) last = upto
  if (last <= first) return

  if (output_mode != "compact" && !byday) {
    add_raw(project_key(project, subpath), mode, last - first, estimated)
    return
  }

  cursor = first
  while (cursor < last) {
    finish = last
    for (i = 1; i <= nbound; i++) {
      if (bound[i] > cursor) {
        if (bound[i] < finish) finish = bound[i]
        break
      }
    }
    day = day_at(cursor)
    if (output_mode == "compact")
      add_compact(day, project, subpath, mode, finish - cursor,
                  estimated ? finish - cursor : 0)
    else {
      bucket = day
      add_raw(bucket, mode, finish - cursor, estimated)
    }
    cursor = finish
  }
}

function id_value(value) { return (value == "" || value == "-") ? "*" : value }
function ids_match(active, terminal) {
  return active == "*" || terminal == "*" || active == terminal
}

# Synthetic rows are generated by bin/tt only for --by day. Their epoch is the
# actual first instant of a local day, including DST days without 00:00.
$2 == "boundary" {
  if (nbound > 0) dayend[boundday[nbound]] = $3 + 0
  bound[++nbound] = $3 + 0
  boundday[nbound] = $1
  daystart[$1] = $3 + 0
  next
}

NF < 11 { next }

# A compact total represents one complete local day. CLI ranges also use local
# day boundaries, so totals are either included whole or excluded whole.
$2 == "total" {
  total_start = $3 + 0; total_end = $4 + 0
  total_mode = $7; total_project = $8; total_subpath = $9
  total_seconds = $11 + 0
  total_estimated = (NF >= 12 ? $12 + 0 : 0)
  if (total_start < since || total_start >= upto) next
  queue_total(total_project, total_subpath, total_mode, total_start, total_end,
              total_seconds, total_estimated)
  next
}

# Carry rows retain only reconstruction state that can affect an interval after
# a compacted boundary. They are internal to current-<machine>.tsv.
$2 == "state" {
  machine = $5; harness = $6; mode = $7; project = $8; subpath = $9
  session = $10
  stream = machine SUBSEP harness SUBSEP session SUBSEP project SUBSEP subpath
  previous_at[stream] = $3 + 0
  state_floor[stream] = $4 + 0
  previous_mode[stream] = mode
  previous_project[stream] = project
  previous_subpath[stream] = subpath
  previous_event[stream] = $11
  active_turn[stream] = ($12 == "-" ? "" : $12)
  lifecycle_epoch[stream] = $13 + 0
  if ($14 ~ /^[0-9]+$/) {
    pending_stop[stream] = $14 + 0
    pending_words[stream] = $15
    pending_project[stream] = $16
    pending_subpath[stream] = $17
    if (NF >= 18 && $18 ~ /^[0-9]+$/) pending_floor[stream] = $18 + 0
  }
  smachine[stream] = machine; sharness[stream] = harness
  ssession[stream] = session
  next
}

$2 == "state-tool" || $2 == "state-agent" {
  machine = $5; harness = $6; project = $8; subpath = $9; session = $10
  stream = machine SUBSEP harness SUBSEP session SUBSEP project SUBSEP subpath
  lifecycle_key = stream SUBSEP ($12 + 0) SUBSEP $11
  if ($2 == "state-tool" && !tool_open[lifecycle_key]) {
    tool_open[lifecycle_key] = 1
    active_tools[stream]++
  } else if ($2 == "state-agent" && !agent_open[lifecycle_key]) {
    agent_open[lifecycle_key] = 1
    active_agents[stream]++
  }
  next
}

$2 == "span" {
  queue_interval($8, $9, "manual", $3 + 0, $4 + 0, 0)
  next
}

$2 != "beat" { next }

{
  at = $3 + 0
  machine = $5; harness = $6; mode = $7; project = $8; subpath = $9
  session = $10; event = $11
  turn = (NF >= 12 ? id_value($12) : "*")
  tool = (NF >= 13 ? id_value($13) : "*")
  agent = (NF >= 14 ? id_value($14) : "*")
  words = (NF >= 16 ? $16 : "-")
  session_source = (NF >= 17 ? $17 : "-")
  stream = machine SUBSEP harness SUBSEP session SUBSEP project SUBSEP subpath
  smachine[stream] = machine; sharness[stream] = harness
  ssession[stream] = session

  if (output_mode == "state" && state_at > 0 && at >= state_at && !snapshot_done)
    snapshot_state()

  # A resumed session keeps its id, and the id is part of the stream key, so a
  # SessionStart can arrive after a turn that no terminal event ever closed.
  # Codex also emits SessionStart with source=compact while the same turn is
  # still running; that continuation must preserve the active lifecycle state.
  if (event == "SessionStart" &&
      !(harness == "codex" && session_source == "compact")) {
    active_turn[stream] = ""
    lifecycle_epoch[stream]++
    active_tools[stream] = 0
    active_agents[stream] = 0
  }

  if (stream in previous_at) {
    elapsed = at - previous_at[stream]
    known_active = (active_turn[stream] != "" || active_tools[stream] > 0 || active_agents[stream] > 0)

    # A prompt arriving while a different turn is still open shows that the
    # earlier turn ended without recording a terminal event -- an interrupt, or
    # a harness that has no hook for one. Its end is unknown, so the gap falls
    # back to the idle rule instead of counting as the agent working. Wildcard
    # ids, which is what a legacy row carries, never trigger this.
    if (event == "UserPromptSubmit" && active_turn[stream] != "" &&
        !ids_match(active_turn[stream], turn))
      known_active = 0

    # Stop ends known activity. Only a timely paired Stop-to-prompt gap is
    # inferred as review/composition; a solo return is handled by its bounded
    # estimate below, and other post-Stop gaps remain idle.
    if (previous_event[stream] == "Stop") {
      inferred = (event == "UserPromptSubmit" && previous_mode[stream] == "paired" && elapsed <= gap)
      known_active = 0
    } else {
      inferred = (elapsed <= gap)
    }

    # Activity marked by an open turn, tool, or subagent counts regardless of
    # TT_IDLE_GAP, so the ceiling is what stops an event that never arrived from
    # counting unbounded time. Counting runs forward from the beat that marked
    # the activity, so a genuinely long tool call keeps the ceiling's worth of
    # it rather than being discarded whole.
    count_to = at
    if (known_active && max_active > 0 && elapsed > max_active)
      count_to = previous_at[stream] + max_active

    if (elapsed > 0 && (known_active || inferred)) {
      interval_from = previous_at[stream]
      if (stream in state_floor && state_floor[stream] > interval_from)
        interval_from = state_floor[stream]
      queue_interval(previous_project[stream], previous_subpath[stream],
                     previous_mode[stream], interval_from, count_to, 0)
    }
  }
  delete state_floor[stream]

  # A reading estimate is created only when the very next event on this stream
  # is the user's return. This prevents overlap with later observed activity.
  if (event == "UserPromptSubmit" && stream in pending_stop) {
    elapsed = at - pending_stop[stream]
    if (elapsed > 0 && reading_wpm > 0 &&
        pending_words[stream] ~ /^[0-9]+$/ && pending_words[stream] > 0) {
      seconds = int(pending_words[stream] * 60 / reading_wpm + 0.5)
      if (seconds > elapsed) seconds = elapsed
      if (seconds > max_reading) seconds = max_reading
      estimate_from = at - seconds
      if (stream in pending_floor && pending_floor[stream] > estimate_from)
        estimate_from = pending_floor[stream]
      queue_interval(pending_project[stream], pending_subpath[stream], "paired",
                     estimate_from, at, 1)
      if (output_mode == "state" && stream in snap_pending_stop)
        snap_pending_accounted[stream] = 1
    }
    delete pending_stop[stream]
    delete pending_words[stream]
    delete pending_project[stream]
    delete pending_subpath[stream]
    delete pending_floor[stream]
  } else if (event != "Stop" && stream in pending_stop && at > pending_stop[stream]) {
    delete pending_stop[stream]
    delete pending_words[stream]
    delete pending_project[stream]
    delete pending_subpath[stream]
    delete pending_floor[stream]
  }

  # Update lifecycle state after measuring the interval ending at this
  # event. Starts mark activity forward; matching terminal events close it at
  # their own timestamp.
  if (event == "UserPromptSubmit") {
    active_turn[stream] = turn
  } else if (event == "Stop" || event == "Interrupt" || event == "StopFailure") {
    if (active_turn[stream] == "" || ids_match(active_turn[stream], turn)) {
      active_turn[stream] = ""
      lifecycle_epoch[stream]++
      active_tools[stream] = 0
      active_agents[stream] = 0
    }
  } else if (event == "SessionEnd") {
    active_turn[stream] = ""
    lifecycle_epoch[stream]++
    active_tools[stream] = 0
    active_agents[stream] = 0
  }

  if (event == "PreToolUse") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP tool
    if (!tool_open[lifecycle_key]) {
      tool_open[lifecycle_key] = 1
      active_tools[stream]++
    }
  } else if (event == "PostToolUse" || event == "PostToolUseFailure" ||
             event == "PermissionDenied") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP tool
    if (tool_open[lifecycle_key]) {
      delete tool_open[lifecycle_key]
      if (active_tools[stream] > 0) active_tools[stream]--
    } else if (tool == "*" && active_tools[stream] > 0) {
      # A terminal event carrying no tool id names no single open call, so it
      # closes them all. Leaving them open would mark activity indefinitely.
      active_tools[stream] = 0
    }
  }

  if (event == "SubagentStart") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP agent
    if (!agent_open[lifecycle_key]) {
      agent_open[lifecycle_key] = 1
      active_agents[stream]++
    }
  } else if (event == "SubagentStop") {
    lifecycle_key = stream SUBSEP lifecycle_epoch[stream] SUBSEP agent
    if (agent_open[lifecycle_key]) {
      delete agent_open[lifecycle_key]
      if (active_agents[stream] > 0) active_agents[stream]--
    }
  }

  if (event == "Stop") {
    if (mode == "solo" && words ~ /^[0-9]+$/ && words > 0) {
      pending_stop[stream] = at
      pending_words[stream] = words
      pending_project[stream] = project
      pending_subpath[stream] = subpath
      delete pending_floor[stream]
    } else {
      delete pending_stop[stream]
      delete pending_words[stream]
      delete pending_project[stream]
      delete pending_subpath[stream]
      delete pending_floor[stream]
    }
  }

  previous_at[stream] = at
  previous_mode[stream] = mode
  previous_event[stream] = event
  previous_project[stream] = project
  previous_subpath[stream] = subpath
}

function dash(value) { return value == "" ? "-" : value }

function snapshot_state(   stream, key) {
  snapshot_done = 1
  for (stream in previous_at) {
    snap_previous_at[stream] = previous_at[stream]
    snap_previous_mode[stream] = previous_mode[stream]
    snap_previous_project[stream] = previous_project[stream]
    snap_previous_subpath[stream] = previous_subpath[stream]
    snap_previous_event[stream] = previous_event[stream]
    snap_active_turn[stream] = active_turn[stream]
    snap_active_tools[stream] = active_tools[stream]
    snap_active_agents[stream] = active_agents[stream]
    snap_lifecycle_epoch[stream] = lifecycle_epoch[stream]
    snap_machine[stream] = smachine[stream]
    snap_harness[stream] = sharness[stream]
    snap_session[stream] = ssession[stream]
    if (stream in pending_stop) {
      snap_pending_stop[stream] = pending_stop[stream]
      snap_pending_words[stream] = pending_words[stream]
      snap_pending_project[stream] = pending_project[stream]
      snap_pending_subpath[stream] = pending_subpath[stream]
      if (stream in pending_floor) snap_pending_floor[stream] = pending_floor[stream]
    }
  }
  for (key in tool_open) if (tool_open[key]) snap_tool_open[key] = 1
  for (key in agent_open) if (agent_open[key]) snap_agent_open[key] = 1
}

function emit_state(   stream, age, active, recent, key, part, owner) {
  if (!snapshot_done) snapshot_state()
  for (stream in snap_previous_at) {
    age = state_at - snap_previous_at[stream]
    active = (snap_active_turn[stream] != "" || snap_active_tools[stream] > 0 ||
              snap_active_agents[stream] > 0 || stream in snap_pending_stop)
    recent = (age >= 0 && age <= gap)
    if (!active && !recent) continue
    carry[stream] = 1
    pending_boundary = "-"
    if (stream in snap_pending_floor) pending_boundary = snap_pending_floor[stream]
    if (snap_pending_accounted[stream]) pending_boundary = state_at
    printf "-\tstate\t%d\t%d\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%d\t%s\t%s\t%s\t%s\t%s\n",
      snap_previous_at[stream], state_at, snap_machine[stream],
      snap_harness[stream], snap_previous_mode[stream], snap_previous_project[stream],
      snap_previous_subpath[stream], snap_session[stream], snap_previous_event[stream],
      dash(snap_active_turn[stream]), snap_lifecycle_epoch[stream] + 0,
      (stream in snap_pending_stop ? snap_pending_stop[stream] : "-"),
      (stream in snap_pending_stop ? snap_pending_words[stream] : "-"),
      (stream in snap_pending_stop ? snap_pending_project[stream] : "-"),
      (stream in snap_pending_stop ? snap_pending_subpath[stream] : "-"),
      pending_boundary
  }

  for (key in snap_tool_open) if (snap_tool_open[key]) {
    split(key, part, SUBSEP)
    owner = part[1] SUBSEP part[2] SUBSEP part[3] SUBSEP part[4] SUBSEP part[5]
    if (!carry[owner] || part[6] + 0 != snap_lifecycle_epoch[owner]) continue
    printf "-\tstate-tool\t%d\t%d\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%d\n",
      snap_previous_at[owner], state_at, snap_machine[owner], snap_harness[owner],
      snap_previous_mode[owner], snap_previous_project[owner], snap_previous_subpath[owner],
      snap_session[owner], part[7], part[6]
  }
  for (key in snap_agent_open) if (snap_agent_open[key]) {
    split(key, part, SUBSEP)
    owner = part[1] SUBSEP part[2] SUBSEP part[3] SUBSEP part[4] SUBSEP part[5]
    if (!carry[owner] || part[6] + 0 != snap_lifecycle_epoch[owner]) continue
    printf "-\tstate-agent\t%d\t%d\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%d\n",
      snap_previous_at[owner], state_at, snap_machine[owner], snap_harness[owner],
      snap_previous_mode[owner], snap_previous_project[owner], snap_previous_subpath[owner],
      snap_session[owner], part[7], part[6]
  }
}

function add_queued_total(i,   bucket, day) {
  day = day_at(sfirst[i])
  if (output_mode == "compact") {
    add_compact(day, sproject[i], ssubpath[i], smode[i], sseconds[i],
                sestimated[i])
  } else {
    bucket = byday ? day : project_key(sproject[i], ssubpath[i])
    add_raw(bucket, smode[i], sseconds[i], 0)
    estimate[bucket] += sestimated[i]
  }
}

function sort_keys(   i, j, value) {
  # Insertion sort avoids depending on gawk's asorti().
  for (i = 2; i <= nkeys; i++) {
    value = keys[i]; j = i - 1
    while (j >= 1 && keys[j] > value) { keys[j + 1] = keys[j]; j-- }
    keys[j + 1] = value
  }
}

function emit_compact(   i, key, mode, m, seconds, estimated) {
  for (i = 1; i <= nkeys; i++) {
    key = keys[i]
    for (m = 1; m <= 3; m++) {
      mode = (m == 1 ? "paired" : (m == 2 ? "solo" : "manual"))
      seconds = total[key, mode] + 0
      if (seconds <= 0) continue
      estimated = (mode == "paired" ? estimate[key] + 0 : 0)
      printf "%s\ttotal\t%d\t%d\t%s\t-\t%s\t%s\t%s\t-\t%d\t%d\n",
        cday[key], daystart[cday[key]], dayend[cday[key]], compact_machine,
        mode, cproject[key], csubpath[key], seconds, estimated
    }
  }
}

function hm(seconds,   hours, minutes) {
  hours = int(seconds / 3600)
  minutes = int((seconds % 3600) / 60)
  return sprintf("%dh %02dm", hours, minutes)
}

END {
  if (output_mode == "state") {
    emit_state()
  } else {
    for (i = 1; i <= nsummary; i++) add_queued_total(i)
    for (i = 1; i <= ni; i++)
      add_interval(iproject[i], isubpath[i], imode[i], ifirst[i], ilast[i], iestimated[i])

    sort_keys()
    if (output_mode == "compact") {
      emit_compact()
    } else {
      # The display has one-minute resolution. Omit buckets that would render
      # as zero in every additive column instead of showing an all-zero row.
      shown = 0
      for (i = 1; i <= nkeys; i++) {
        key = keys[i]
        seconds = total[key, "paired"] + total[key, "solo"] + total[key, "manual"]
        if (seconds >= 60) keys[++shown] = key
      }
      nkeys = shown

      width = 7
      for (i = 1; i <= nkeys; i++) if (length(keys[i]) > width) width = length(keys[i])
      format = "%-" width "s  %9s %9s %9s %9s %9s\n"

      if (nkeys > 0)
        printf format, (byday ? "DAY" : "PROJECT"), "PAIRED", "SOLO", "MANUAL", "ESTIMATED", "TOTAL"

      grand_paired = 0; grand_solo = 0; grand_manual = 0; grand_estimate = 0
      for (i = 1; i <= nkeys; i++) {
        key = keys[i]
        paired = total[key, "paired"] + 0
        solo = total[key, "solo"] + 0
        manual = total[key, "manual"] + 0
        estimated = estimate[key] + 0
        grand_paired += paired; grand_solo += solo; grand_manual += manual
        grand_estimate += estimated
        printf format, key, hm(paired), hm(solo), hm(manual), hm(estimated), hm(paired + solo + manual)
      }

      if (nkeys > 0)
        printf format, "TOTAL", hm(grand_paired), hm(grand_solo), hm(grand_manual),
               hm(grand_estimate), hm(grand_paired + grand_solo + grand_manual)
      else print "no events in range"
    }
  }
}
